enabled = true;
sign_authenticated = true;
sign_local = true;
use_domain = "envelope";
use_redis = false;
path = "/etc/rspamd/keys/mail.private";
selector = "mail";
sign_networks = ["172.16.0.0/12", "127.0.0.0/8"];
try_fallback = true;
allow_username_mismatch = true;
