[relay-postfix-sasl]
enabled  = true
filter   = relay-postfix-sasl
logpath  = /var/log/relay-postfix.log
maxretry = 5
findtime = 300
bantime  = 3600
action   = ufw[name=relay-sasl, port="25,587", protocol=tcp]
