Mode                    sv
Syslog                  yes
SyslogSuccess           yes
LogWhy                  yes

# Ascolta su tutte le interfacce del container
Socket                  inet:8891@0.0.0.0

KeyFile                 /etc/opendkim/keys/mail.private
Selector                mail

SigningTable            refile:/etc/opendkim/SigningTable
KeyTable                /etc/opendkim/KeyTable

Canonicalization        relaxed/simple
SignatureAlgorithm      rsa-sha256

InternalHosts           /etc/opendkim/InternalHosts
